# -*- coding: utf-8 -*-
"""disponibilizacipon.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-zbyuvgrw_bCZs-wpz2-fA0VKAzB41TM
"""

#Librerias
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.metrics import r2_score, roc_auc_score
from sklearn.model_selection import train_test_split
import nltk
import re
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from nltk.corpus import stopwords
import joblib
from flask import Flask, request, jsonify
from flask_restx import Api, Resource, fields

import nltk
import os

try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt')

# Carga de datos de archivo .csv
dataTraining = pd.read_csv('https://github.com/albahnsen/MIAD_ML_and_NLP/raw/main/datasets/dataTraining.zip', encoding='UTF-8', index_col=0)
dataTesting = pd.read_csv('https://github.com/albahnsen/MIAD_ML_and_NLP/raw/main/datasets/dataTesting.zip', encoding='UTF-8', index_col=0)

dataTraining.reset_index(drop=True, inplace=True)
dataTraining = dataTraining.tail(800)

def limpiar_datos(text):
    text = text.lower()
    text = re.sub(r'w+:/[2][dw-]+(.dw-]+)*(?:/?[:^s/])*/', '', text)  # Eliminar URLs
    text = re.sub(r'[^a-zA-Z0-9\s!-]', '', text)  # Elimina puntuación (excepto ! y -)
    return text

dataTraining['plot'] = dataTraining['plot'].apply(limpiar_datos)
dataTesting['plot'] = dataTesting['plot'].apply(limpiar_datos)

dataTraining['title'] = dataTraining['title'].apply(limpiar_datos)
dataTesting['title'] = dataTesting['title'].apply(limpiar_datos)

#Eliminar stopwords
nltk.download('stopwords')
stop_words = set(stopwords.words('english'))

# Definir tus propias stopwords adicionales
mis_stopwords = { 'named','movie', 'like', 'way', 'help', 'film', 'scene', 'character', 'plot', 'also', 'get', 'must', 'go', 'old', 'young', 'u', 'gets', 'finds', 'soon'}  # Ejemplo
todas_las_stopwords = stop_words.union(mis_stopwords)

#Nuevas variables

def nuevas_caracteristicas(df):
  df['length_title'] = df['title'].apply(lambda s: len(s))
  df['length_body'] = df['plot'].apply(lambda s: len(s))
  df['antiguedad'] = 2025 - df['year'].astype(int)
  df['decada'] = df['year'].apply(lambda x: int(x/10)*10)
  df['num_words_title'] = df['title'].apply(lambda s: len(s.split()))
  df['num_words_plot'] = df['plot'].apply(lambda s: len(s.split()))
  df['has_number_title'] = df['title'].apply(lambda s: any(char.isdigit() for char in s))

  return df

dataTraining = nuevas_caracteristicas(dataTraining)
dataTesting = nuevas_caracteristicas(dataTesting)

#Eliminar Plots atipicos
quantile_10 = dataTraining[['length_body']].quantile(0.10)[0].astype(float)
quantile_90 = dataTraining[['length_body']].quantile(0.90)[0].astype(float)

dataTraining = dataTraining[(dataTraining['length_body']<=quantile_90) & (dataTraining['length_body']>=quantile_10)]

#Normalización de las columnas calculadas
dataTraining.columns
columnas_add = dataTraining.columns[6:]
columnas_add

"""def columnas_normalizar(df):
       columas_normalizar = ['antiguedad','length_body','length_title', 'num_words_title', 'num_words_plot',
       'has_number_title']
       scaler = MinMaxScaler()
       df[columas_normalizar] = scaler.fit_transform(df[columas_normalizar])
       df[columas_normalizar].head()
       return df"""


#Normalización de las columnas calculadas

columas_normalizar = ['antiguedad','length_body','length_title', 'num_words_title', 'num_words_plot',
       'has_number_title']
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dataTraining[columas_normalizar] = scaler.fit_transform(dataTraining[columas_normalizar])
dataTraining[columas_normalizar].head()

#dividir entrenamiento y validación
dataTraining, dataValidation = train_test_split(dataTraining, test_size=0.2, random_state=42)

#Lematización
# Lematización
import nltk
from nltk.stem import WordNetLemmatizer
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('averaged_perceptron_tagger')

def lematizar(text):
    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return ' '.join(tokens)


def lematizar_titulo(text):
    lemmatizer = WordNetLemmatizer()
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(token) for token in tokens]
    return ' '.join(tokens)
dataTraining['plot'] = dataTraining['plot'].apply(lematizar)
dataTesting['plot'] = dataTesting['plot'].apply(lematizar)
dataTraining['title'] = dataTraining['title'].apply(lematizar_titulo)
dataTesting['title'] = dataTesting['title'].apply(lematizar_titulo)

# Utilizamos tfidf_vectorizer

 # Convertimos el conjunto de stopwords a una lista
todas_las_stopwords
lista = list(todas_las_stopwords)

tfidf_vectorizer = TfidfVectorizer(max_features=10000, ngram_range=(1, 3), stop_words = lista, norm='l2', use_idf= True)

X_dtm_plot = tfidf_vectorizer.fit_transform(dataTraining['plot'])
X_validation_dtm_plot = tfidf_vectorizer.transform(dataValidation['plot'])  # Usa .transform

X_dtm_title = tfidf_vectorizer.fit_transform(dataTraining['title'])
X_validation_dtm_title = tfidf_vectorizer.transform(dataValidation['title'])  # Usa .transform

# Normalización de los vectores calculados X_dtm_plot X_validation_dtm_plot X_dtm_title X_validation_dtm_title

from sklearn.preprocessing import MinMaxScaler
scaler_plot = MinMaxScaler() # Create a separate scaler for plot
scaler_title = MinMaxScaler() # Create a separate scaler for title


#Los convertimos en arreglos Plot
X_dtm_plot = X_dtm_plot.toarray()
X_validation_dtm_plot  = X_validation_dtm_plot.toarray()

# Convertimos la data y transformaos plot
X_dtm_plot = scaler_plot.fit_transform(X_dtm_plot)
X_validation_dtm_plot = scaler_plot.transform(X_validation_dtm_plot)


#Los convertimos en arreglos Title
X_dtm_title = X_dtm_title.toarray()
X_validation_dtm_title  = X_validation_dtm_title.toarray()

# Convertimos la data y transformaos Title
X_dtm_title = scaler_title.fit_transform(X_dtm_title)
# Corrected: Use the scaler_title and transform X_validation_dtm_title
X_validation_dtm_title = scaler_title.transform(X_validation_dtm_title)

#Concatenar matrices
dataTraining.reset_index(inplace=True, drop=True) # Reset index of the dataTraining DataFrame
dataValidation.reset_index(inplace=True, drop=True) # Reset index of the dataTraining DataFrame

# Concatenar matrices
x_concat =  pd.concat([pd.DataFrame(X_dtm_plot), pd.DataFrame(X_dtm_title),  dataTraining[columnas_add]], axis = 1)
x_validation_concat =  pd.concat([pd.DataFrame(X_validation_dtm_plot),pd.DataFrame(X_validation_dtm_title),  dataValidation[columnas_add]], axis = 1)

#x_concat =  pd.concat([ dataTraining[columnas_add]], axis = 1)
#x_validation_concat =  pd.concat([ dataValidation[columnas_add]], axis = 1)


# Convertir todos los nombres de columna a strings para evitar el TypeError
x_concat.columns = x_concat.columns.astype(str)
x_validation_concat.columns = x_validation_concat.columns.astype(str)

# Definición de variable de interés (y)
import ast  # Importa el módulo ast
from sklearn.preprocessing import MultiLabelBinarizer

# Asumiendo que 'genres' son strings que representan listas
# Use a try-except block to handle potential errors during literal evaluation
dataTraining['genres'] = dataTraining['genres'].map(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)
dataValidation['genres'] = dataValidation['genres'].map(lambda x: ast.literal_eval(x) if isinstance(x, str) else x)

le = MultiLabelBinarizer()
y_train_genres = le.fit_transform(dataTraining['genres'])
y_validation_genres = le.transform(dataValidation['genres'])

# Separación de variables predictoras (X) y variable de interés (y) en set de entrenamiento y test usandola función train_test_split
X_train, X_test, y_train_genres, y_test_genres = train_test_split(x_concat, y_train_genres , test_size=0.33, random_state=42)

from sklearn.linear_model import LogisticRegression

lr = OneVsRestClassifier(LogisticRegression() )
lr.fit(X_train, y_train_genres)
y_pred_genres_proba = lr.predict_proba(X_test)

roc_auc_score(y_test_genres, y_pred_genres_proba, average='macro')

joblib.dump(lr, 'randomforestMl', compress = 3)

app = Flask(__name__)

api = Api(
    app,
    version='1.0',
    title='PrediccionMl',
    description='PrediccionMl')

ns = api.namespace('PreddiccionPlotsPeliculas',
     description='PreddiccionPlotsPeliculas')

# Definición argumentos o parámetros de la API
parser = ns.parser()

parser.add_argument(
  'year',
  type=int,
  required=True,
  help='Ingresa el anno de la película',
  location='args')

parser.add_argument(
  'title',
  type=str,
  required=True,
  help='Ingresa el título de la película',
  location='args')

parser.add_argument(
  'plot',
  type=str,
  required=True,
  help='Ingresa el plot de la película',
  location='args')

resource_fields = api.model('Resource', {
    'result': fields.String,
})

@ns.route('/')
class PrediccionMlXG(Resource):

 @api.doc(parser=parser)
 @api.marshal_with(resource_fields)
 def get(self):
     args = parser.parse_args()

     # Crear un DataFrame con los datos de entrada
     input_data = pd.DataFrame([args])

     # Aplicar las mismas transformaciones que en el entrenamiento
     input_data['plot'] = input_data['plot'].apply(limpiar_datos)
     input_data['title'] = input_data['title'].apply(limpiar_datos)
     input_data = nuevas_caracteristicas(input_data)

    # Normalizar las columnas numéricas **antes** de concatenar
     input_data[columas_normalizar] = scaler.transform(input_data[columas_normalizar])

        # Lematizar las columnas de texto
     input_data['plot'] = input_data['plot'].apply(lematizar)
     input_data['title'] = input_data['title'].apply(lematizar_titulo)

        # Transformar las columnas de texto con el mismo vectorizador
     plot_transformed = tfidf_vectorizer.transform(input_data['plot']).toarray()
     title_transformed = tfidf_vectorizer.transform(input_data['title']).toarray()

        # Crear DataFrames a partir de las matrices transformadas
     plot_df = pd.DataFrame(plot_transformed, index=input_data.index)
     title_df = pd.DataFrame(title_transformed, index=input_data.index)

        # Concatenar las matrices transformadas y las columnas adicionales
     input_data = pd.concat([plot_df, title_df, input_data[columnas_add]], axis=1)

    # Asegurarse de que las columnas estén en el mismo orden que durante el entrenamiento
#input_data.columns = input_data.columns.astype(str)

    #Asegurarse de que tenga el mismo numero de columnas
     missing_cols = set(X_train.columns) - set(input_data.columns)
     for c in missing_cols:
         input_data[c] = 0
        # Ensure the order of column is the same
     input_data = input_data[X_train.columns]

     input_data.columns = input_data.columns.astype(str)

    # Realizar la predicción
     try:
         y_pred_genres_proba = lr.predict_proba(input_data)
         prediction = y_pred_genres_proba.argmax(axis=1)[0]
         diccionario = {i:j for i,j in zip(le.classes_, y_pred_genres_proba[0])}
         dicc = sorted(diccionario.items(), key=lambda x: x[1], reverse=True)
     except ValueError as e:
         print(f"Error en la predicción: {str(e)}")
         prediction = None

     return {
         "result": f'los generos más probables son : {dicc}'
     }, 200
if __name__ == '__main__':
  app.run(debug=True, use_reloader=False, host='0.0.0.0', port=5000)
